AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple Flask web app on EC2 using CloudFormation

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  FlaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  FlaskInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (check region)
      SecurityGroupIds:
        - !Ref FlaskSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 git
          pip3 install flask
          cd /home/ec2-user
          git clone https://github.com/<your-github-username>/flask-app.git
          cd flask-app
          nohup python3 app.py > app.log 2>&1 &

Outputs:
  WebAppURL:
    Description: Flask Web App URL
    Value: !Sub "http://${FlaskInstance.PublicDnsName}:5000"
